# Generated by Django 6.0.1 on 2026-10-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.CharField()),
                ('phone_number', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
